import os

#get all the build variables we need
Import('env', 'project', 'buildmode', 'debugcompilerflags', 'releasecompilerflags', 'linklibraries', 'install_prefix')
localenv = env.Clone()

buildroot = '../../../' + buildmode  #holds the root of the build directory tree
builddir = buildroot + '/' + project   #holds the build directory for this project
targetpath = builddir + '/' + project  #holds the path to the executable in the build directory

localenv.Append(CPPPATH = ['../'])

#specify the build directory
localenv.VariantDir(builddir, ".", duplicate=0)


# the compiler tool (static for now)
source = ['keyvicompiler.cpp']
keyvicompiler = localenv.Program(target = targetpath, source = source,
                                      LIBS = linklibraries)

# installer
prefix = install_prefix

localenv.Alias("install", localenv.Install(os.path.join(prefix, "bin"), keyvicompiler))
