version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Docker images for cibuildwheel
  - package-ecosystem: "docker"
      directories:
      - "/docker/manylinux-builder-aarch64"
      - "/docker/manylinux-builder-x86_64"
      - "/docker/musllinux-builder-aarch64"
      - "/docker/musllinux-builder-x86_64"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"
