name: cpp-linter
on:
  pull_request:
    paths: ['**.cpp', '**.h', '**.hpp', '**CMakeLists.txt', '**.cmake', '.github/workflows/cpp-linter.yml']

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsnappy-dev libzzip-dev zlib1g-dev libboost-all-dev

      - uses: actions/checkout@v5

      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.16.5
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 21
          extra-args: '-std=c++17'
          style: ''  # disable clang-format checks.
          tidy-checks: '' # Use .clang-tidy config file.
