name: Manylinux

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  manylinux:
    strategy:
      matrix:
        python_path: [ cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39 ]

    runs-on: ubuntu-latest
    container:
      image: keyvidev/manylinux-builder
      env:
        PYTHON_PATH: ${{ matrix.python_path }}
    steps:
      - uses: actions/checkout@v2
      - name: Build manylinux package
        run: |
          cd python

          PYBIN=/opt/python/${PYTHON_PATH}/bin

          ${PYBIN}/pip install -r requirements.txt

          # Build
          ${PYBIN}/python setup.py bdist_wheel -d dist

          # Bundle external shared libraries into the wheels
          for wheel in dist/*.whl; do
              auditwheel repair ${wheel} -w wheelhouse/
          done

          # Install and test
          ${PYBIN}/pip install keyvi --no-index -f wheelhouse/

          cd ~
          ${PYBIN}/py.test ${GITHUB_WORKSPACE}/python/tests/
          ${PYBIN}/py.test ${GITHUB_WORKSPACE}/python/integration-tests/

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          PYPI_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          PYBIN=/opt/python/${PYTHON_PATH}/bin
          ${PYBIN}/python -m twine upload -u __token__ -p "${PYPI_PASSWORD}" python/wheelhouse/*
