name: Rust

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnappy-dev libzzip-dev zlib1g-dev libboost-all-dev
    - name: Code fomatting
      run: cargo fmt --manifest-path rust/Cargo.toml -- --check
    - name: Build
      run: cargo build --verbose --manifest-path rust/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path rust/Cargo.toml

  build_latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v4
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libsnappy-dev libzzip-dev zlib1g-dev libboost-all-dev
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose --manifest-path rust/Cargo.toml
      - run: cargo build --verbose --manifest-path rust/Cargo.toml
      - run: cargo test --verbose --manifest-path rust/Cargo.toml

